$dbFiles = @{
    "exp_guild.yml" = "GUILD_EXP_DB"
    "instance_db.yml" = "INSTANCE_DB"
    "const.yml" = "CONSTANT_DB"
    "item_db.yml" = "ITEM_DB"
    "item_randomopt_db.yml" = "RANDOM_OPTION_DB"
    "item_randomopt_group.yml" = "RANDOM_OPTION_GROUP"
    "item_group_db.yml" = "ITEM_GROUP_DB"
    "item_combos.yml" = "COMBO_DB"
    "laphine_synthesis.yml" = "LAPHINE_SYNTHESIS_DB"
    "laphine_upgrade.yml" = "LAPHINE_UPGRADE_DB"
    "item_reform.yml" = "ITEM_REFORM_DB"
    "item_enchant.yml" = "ITEM_ENCHANT_DB"
    "item_packages.yml" = "ITEM_PACKAGE_DB"
    "item_cash.yml" = "ITEM_CASH_DB"
    "skill_db.yml" = "SKILL_DB"
    "abra_db.yml" = "ABRA_DB"
    "magicmushroom_db.yml" = "MAGIC_MUSHROOM_DB"
    "spellbook_db.yml" = "READING_SPELLBOOK_DB"
    "create_arrow_db.yml" = "CREATE_ARROW_DB"
    "mob_db.yml" = "MOB_DB"
    "mob_chat_db.yml" = "MOB_CHAT_DB"
    "mob_item_ratio.yml" = "MOB_ITEM_RATIO_DB"
    "mob_avail.yml" = "MOB_AVAIL_DB"
    "mob_summon.yml" = "MOB_SUMMONABLE_DB"
    "level_penalty.yml" = "PENALTY_DB"
    "job_stats.yml" = "JOB_STATS"
    "skill_tree.yml" = "SKILL_TREE_DB"
    "statpoint.yml" = "STATPOINT_DB"
    "attendance.yml" = "ATTENDANCE_DB"
    "reputation.yml" = "REPUTATION_DB"
    "captcha_db.yml" = "CAPTCHA_DB"
    "size_fix.yml" = "SIZE_FIX_DB"
    "refine.yml" = "REFINE_DB"
    "status.yml" = "STATUS_DB"
    "enchantgrade.yml" = "ENCHANTGRADE_DB"
    "attr_fix.yml" = "ATTRIBUTE_DB"
    "castle_db.yml" = "CASTLE_DB"
    "guild_skill_tree.yml" = "GUILD_SKILL_TREE_DB"
    "pet_db.yml" = "PET_DB"
    "homunculus_db.yml" = "HOMUNCULUS_DB"
    "exp_homun.yml" = "HOMUN_EXP_DB"
    "mercenary_db.yml" = "MERCENARY_DB"
    "elemental_db.yml" = "ELEMENTAL_DB"
    "quest_db.yml" = "QUEST_DB"
    "achievement_db.yml" = "ACHIEVEMENT_DB"
    "achievement_level_db.yml" = "ACHIEVEMENT_LEVEL_DB"
    "battleground_db.yml" = "BATTLEGROUND_DB"
    "stylist.yml" = "STYLIST_DB"
    "map_drops.yml" = "MAP_DROP_DB"
}

foreach ($item in $dbFiles.GetEnumerator()) {
    $file = $item.Key
    $type = $item.Value
    $content = "Header:`n  Type: $type`n  Version: 1`n`nBody: []"
    $path = Join-Path (Get-Location) "db\import\$file"
    [System.IO.File]::WriteAllText($path, $content)
}
Write-Host "Updated $($dbFiles.Count) YAML files with headers (LF, no BOM)."
